[package]
name = "wasmer-wat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmtime = "6"
wasmi = "0.13.2"
wat = "1"

