[package]
name = "wasmer428"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmer = "4.2.8"
wasmer-compiler-singlepass = "4.2.8"
wasmer-middlewares = "4.2.8"
