[package]
edition = "2018"
name = "environmental"
version = "1.1.3"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Set scope-limited values can can be accessed statically"
license = "Apache-2.0"

members = [
    "mult-env",
]

[features]
default = ["std"]
std = []
